services:
  - type: web
    name: nutritrack-app
    env: python
    plan: free # Используем бесплатный тариф
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run main.py --server.port $PORT --server.headless true --server.enableCORS false"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8 # Укажем версию Python как в pyproject.toml 
