[server]
headless = true
enableCORS = false
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#28a745"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans-serif"
